version: '3.7'
services:
  app:
    image: serversideup/php:beta-8.3-fpm-nginx
    container_name: laravel11_webserver
    ports:
      - '8888:80'
      - '444:443'
    volumes:
      - .:/var/www/html/:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - AUTORUN_ENABLED=false
      - SSL_MODE=mixed
    networks:
      - laravel11_network
  task:
    build:
      context: .
      dockerfile: Dockerfile-cli
    container_name: laravel11_task
    command: ["gosu", "www-data", "/usr/local/bin/php", "artisan", "schedule:work"]
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_FPM_POOL_NAME: "laravel11_task"
    networks:
      - laravel11_network
  queue:
    build:
      context: .
      dockerfile: Dockerfile-cli
    container_name: laravel11_queue
    command: ["gosu", "www-data", "/usr/local/bin/php", "artisan", "queue:work"]
    volumes:
      - .:/var/www/html/:cached
    environment:
      PHP_FPM_POOL_NAME: "laravel11_queue"
    networks:
      - laravel11_network
  redis:
    container_name: laravel11_redis
    image: redis:7.0-alpine
    command: "redis-server --appendonly yes --requirepass redispassword"
    networks:
      - laravel11_network
  db:
    container_name: laravel11_db
    image: mysql:8.3
    ports:
      - '3305:3306'
    volumes:
      - laravel11-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    networks:
      - laravel11_network

volumes:
  laravel11-db:
    driver: local

networks:
  laravel11_network:
